null safety widgets instance
AbdulRahmanAlHamali/flutter_typeahead pull request #408
Opened 2022-06-02 10:52 UTC by nathanielajayi7

The instance of WidgetsBinding cannot be accessed unconditionally

2022-06-07 14:33 UTC, zaikavova requested changes
Remove downgrading changes

2022-06-07 14:33 UTC, zaikavova commented on lib/src/flutter_typeahead.dart
> +    WidgetsBinding.instance?.removeObserver(this);
Flutter 3.0 now gives the required value, so this is not needed.

2022-06-07 14:33 UTC, zaikavova commented on lib/src/cupertino_flutter_typeahead.dart
> +    WidgetsBinding.instance?.addPostFrameCallback((duration) {
Flutter 3.0 now gives the required value, so this is not needed.

2022-06-07 14:33 UTC, zaikavova commented on lib/src/cupertino_flutter_typeahead.dart
> +    WidgetsBinding.instance?.addObserver(this);
Flutter 3.0 now gives the required value, so this is not needed.

2022-06-07 14:33 UTC, zaikavova commented on lib/src/cupertino_flutter_typeahead.dart
> +    WidgetsBinding.instance?.removeObserver(this);
Flutter 3.0 now gives the required value, so this is not needed.

2022-06-07 14:33 UTC, zaikavova commented on lib/src/flutter_typeahead.dart
> +    WidgetsBinding.instance?.addObserver(this);
Flutter 3.0 now gives the required value, so this is not needed.

2022-06-07 14:33 UTC, zaikavova commented on lib/src/flutter_typeahead.dart
> +    WidgetsBinding.instance?.addPostFrameCallback((duration) {
Flutter 3.0 now gives the required value, so this is not needed.

2022-06-19 13:06 UTC, clragon commented
this merge request would undo migration to flutter 3.0
please update your flutter version.
if you cannot, it is possible to introduce a backwards compatible version of this code,
as instructed here:

https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code

2022-07-23 17:08 UTC, sjmcdowall commented
As per clragon -- this PR would undo the 3.0 flutter  .. so won't be done ..

2022-07-23 17:08 UTC, closed without merging